kernel: use grep check inode_lock
in fact we can't do __weak for them, because signature mismatch

In file included from /tmp/src/android/kernel/samsung/exynos7885/drivers/kernelsu/dynamic_manager.c:25:
/tmp/src/android/kernel/samsung/exynos7885/drivers/kernelsu/kernel_compat.h:141:1: warning: attribute declaration must precede definition [-Wignored-attributes]
__weak void inode_lock(struct inode *inode)
^
/tmp/src/android/kernel/samsung/exynos7885/include/linux/compiler-gcc.h:107:32: note: expanded from macro '__weak'
^
/tmp/src/android/kernel/samsung/exynos7885/include/linux/fs.h:771:20: note: previous definition is here
static inline void inode_lock(struct inode *inode)
^
In file included from /tmp/src/android/kernel/samsung/exynos7885/drivers/kernelsu/dynamic_manager.c:25:
/tmp/src/android/kernel/samsung/exynos7885/drivers/kernelsu/kernel_compat.h:141:13: error: redefinition of 'inode_lock'
__weak void inode_lock(struct inode *inode)
^
/tmp/src/android/kernel/samsung/exynos7885/include/linux/fs.h:771:20: note: previous definition is here
static inline void inode_lock(struct inode *inode)

In file included from /tmp/src/android/kernel/samsung/exynos7885/drivers/kernelsu/throne_tracker.c:18:
/tmp/src/android/kernel/samsung/exynos7885/drivers/kernelsu/kernel_compat.h:146:1: warning: attribute declaration must precede definition [-Wignored-attributes]
__weak void inode_unlock(struct inode *inode)
^
/tmp/src/android/kernel/samsung/exynos7885/include/linux/compiler-gcc.h:107:32: note: expanded from macro '__weak'
^
/tmp/src/android/kernel/samsung/exynos7885/include/linux/fs.h:776:20: note: previous definition is here
static inline void inode_unlock(struct inode *inode)
^
In file included from /tmp/src/android/kernel/samsung/exynos7885/drivers/kernelsu/throne_tracker.c:18:
/tmp/src/android/kernel/samsung/exynos7885/drivers/kernelsu/kernel_compat.h:146:13: error: redefinition of 'inode_unlock'
__weak void inode_unlock(struct inode *inode)
^
/tmp/src/android/kernel/samsung/exynos7885/include/linux/fs.h:776:20: note: previous definition is here
static inline void inode_unlock(struct inode *inode)

Signed-off-by: AlexLiuDev233 <wzylin11@outlook.com>